require('dotenv').config(); // lee DATABASE_URL del .env
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const items = [
{ descripcion: "PISTOLA DE TEMPERATURA 220 V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOEMTRO OXIGENO - LINDE", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO GAS LINDE", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TARJETAS DE EXPANSIÓN VACOM", cantidad: 4, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTROLADOR TEMPERADTURA EURO HEATER EAT-402SSR", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO IA/QA SIEMENS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "INTERFASE SIMOTIC SIEMENS PARA MODULO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CPU CLARIFICADOR PROGRAMADO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PANTALLA ADOSABLE HONEYWELL", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TAIMER AT8N", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SELENOIDE DE GAS 3/8 - 220 V", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PRESOSTATO 0.2-8 BAR DANFOSS", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "FUENTE 12 VDC - 4.5 A", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TACOMETRO MP5W-45 AUTONIC", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "INDICADOR DE AMPERAJE MT W. AA-4N", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR PROXIMIDAD CAPACITIVO CR30-15DP", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR INDUCTIVO 220VAC - LM30 2015JC", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "AMPLIFICADOR ULTRAVIOLETA HONEYWELL", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR INDUCTIVO XSAV12373", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TARJETA OPTO BALANZA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TARJETA FUENTE CONTADOR DE GAS", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTROLADOR TEMPERATURA Y PT100 (BTC9100)", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PANTALLA ADOSABLE SEW", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONVERTIDOR DE PSI DE 4-20 MA ELECTRONEUMATICA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TARJETA DE CONTROL ARRANCADOR SCHNEIDER", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TARJETA DE BALANZA CELDA DE CARGA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SWITCHS MODULO DE COMUNICACION ETERNET SIEMENS", cantidad: 2, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONECTOR PARA ACTUADORES SERVO CALDERO", cantidad: 6, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PLC SIMATIC S7 1200", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "VENTILADOR 3X3PLG 24 VDC", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "VALVULA RETROLLAMA GAS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSMISOR DE PRESIÓN 0-0.25 BAR (G0G2418)", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELE DE SEURIDAD PILZ", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR ULTRASONICO 24VDC / 4-20 MA/ 0-10 MTS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTROLADOR ANTHOME 920", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "AMPERIMETRO MT4WDA4L", cantidad: 3, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "AMPERIMETRO MT4WDA4L", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PANTALLA RICC LAKE", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRAJETA RICE LAKE BALANZA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MOUSE DE COMPUTADORA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONVERTIDOR PARA CONEXIÓN DATA SERVICE / SERVER", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONVERTIDOR 220V / 40 W", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CARRETE DE ESTAÑO 0.25", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CARRETE DE ESTAÑO 2.25", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELE CONTROL WARRICK 26C1B0F", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "POE / COMUNICACION", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSMISOR DE PRESIÓN 4-20 MA, 0-10 BARES 1/4PLG", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "1", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PLC SIEMENS 1200 (1214C)", cantidad: 2, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PLC SIEMENS 1200 (1212C1)", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO ENTRADA/SALIDA DIGITAL - PLC 1200", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO ENTRADA DIGITAL / SALIDA ANALOGICA - PLC 1200", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO ENTRADA ANALOGICA - PLC 1200", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO FUENTE - PLC 1200", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MODULO DE COMUNICACIÓN - PLC 1200", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "JUEGO PLC LOGO SIEMENS", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "ELECTROVALVULA 5/2 VIAS 220V FESTO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSMISOR INDICADOR PRESIÓN YOKOGAWA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSMISOR INDICADOR PRESIÓN YOKOGAWA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSORES HORQUILLA 24VDC PARA NIVEL", cantidad: 3, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "ELECCTROVALVULA 5/2 VIAS 220V", cantidad: 5, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DIODO GRUPO ELECTROGENO M50100TB1600", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSMISOR PRESIÓN 0-16 BAR, 4-20MA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR INDUCTIVO SECRON", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR DE VELOCIDAD FLOWER", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CAJA CON CONVERTIDOR PT100 PR", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR DE LLAMA HLT + CABLE IGNICIÓN", cantidad: 2, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "HMI TANQUE DESAIRADOR CALDERO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "ELECTROVALVULA PARA MANIFOLD SMC 220V 5/2 VIAS", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONVERTIDORES DE PT-100 DE 4-20 MA", cantidad: 10, estado: "BSU", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PT100 0-150 °C", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PT100 0-500°C CON CONVERTIDO 4-20MA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOPOZOS", cantidad: 5, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOCUPLA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOCUPLA 0-100°C HILO 1/4PLG", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "2", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PANTALLA INDICADOR ENDRES HAUSER DE SOLIDO", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTADOR RELE RECHAZO DE CARGA", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CUADERNO 200 HOJAS", cantidad: 8, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PANTALLA MONTACARGA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOUCH SIEMENS KTP-900 BASIC/ TANQUE DECANTADOR PROGRAMADO", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOUCH SIEMENS KTP-700 BASIC/ COCINA PRENSA PROGRAMADO", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOUCH SIEMENS KTP-700 CONFORT / CHATA PROGRAMADO", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOUCH SIEMENS KTP-700 CONFORT / PULIDORA WESTFALIA PROGRAMADO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "FUENTE NUEVO PARA PLC 1500 , 220/14 V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SENSOR ULTRASONICO HART", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "FLUJOMETRO COMPLETO 2PLG YOKOGAWA", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "3", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "INTERRUPTOR TERMICO SCHNEIDER 22-32A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "GUARDAMOTOR SCHNEIDER GV3 48-65A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "INTERRUPTOR TERMICO SCHNEIDER 250A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CAJA BORNERA DE CONTROL 4 MM2 (2X50 UNIDADES)", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CAJA BORNERA DE CONTROL 4 MM2 (25 UNIDADES)", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SELENOIDE DE GAS 3/8 X 220V DANFOS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "VALVULA SELENOIDE 48 VAC", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELE TERMISTOR EATON", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELE TERMICO SIRIUS 12.5-50 A (SIEMENS)", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BLOQUE CONTACTO AUXILIAR - SIEMENS", cantidad: 8, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMICO 5 INES (SIEMENS SIRIUS) - 3A A 10A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "GUARDAMOTOR GV3 (4A)", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTOR LCD 65 /220 VAC SCHNEIDER", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOROIDE 150/5A", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SIRENA 220V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SUPRESOR DE PICOS 2X15A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOROIDE 50/5 A", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMINAL STARFIX 2.5MM GRIS", cantidad: 100, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMINAL STARFIS 4 MM NARANJA", cantidad: 750, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "HOROMETRO MECÁNICO LEGRAND 240V", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BASE CON (RELES 4) (8 PINES) 220V", cantidad: 9, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTOR LC1D4QA BOBINA 220V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTO PARA PULSADOR N.O VERDE", cantidad: 10, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SELECTOR DE 2 POSICIONES", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMINAL PREAISLADO DE ENCHUFE", cantidad: 50, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTOR SIEMENS 110V BOBINA 5.5KW", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BLOCK AUXILIAR GUARDAMOTOR GV2/GV3", cantidad: 4, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "PERNOS INOX 1/4 CABEZA DE COCHE", cantidad: 25, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONECTORES PARA TRANSFORMADOR IGNICIÓN", cantidad: 12, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "LAMPARA ROJA 24 VDC", cantidad: 7, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "GUARDAMOTOR SIEMENS GV2 4A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TEMPORIZADOR SIEMENS 0-100 HORAS (SIRIUS)", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BOBINA PARA CONTACTO LC1D1-150 , 220V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BORNERA DE 70 MM2 LEGRAND", cantidad: 15, estado: "Nuevo", ubicacion: "Electricista", nivel: "4", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "VALVULA INOX 3/8", cantidad: 10, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SWITCHS DIFERENCIADOR DE PRESION (750-15PSI CLEAVERBROOKS)", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RESISNTECIAS 2X20CM 200W/220V", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELES ENCAPSULADOS 8 PINES /220V", cantidad: 8, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TRANSFORMADOR IGNICIÓN 220V", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RESISTENCIA 500W 220V 10X20CM", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO DE 0-300 PSI SISTEMA CONTRAINCENDIOS", cantidad: 9, estado: "BSU", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO DE 1 A 7 BAR 1/4 NPT", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CANDAD PARA BLOQUEO", cantidad: 7, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TOMACORRIENTE MENEKE ADOSABLE 2P+T 32A", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BOYA PARA NIVEL DE TANQUE KF-06", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOMETRO ANALOGICO 0-150°C 1/2NPT", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOMETRO ANALOGICO 0-150°C 1/2NPT", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO PRESIÓN 0-160 PSI 1/2 NPT", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO PRESIÓN 0-160 PSI 1/4 NPT", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO PRESIÓN 0-160 PSI 1/4 NPT", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANOMETRO PRESIÓN 0-100 IN H20", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOMETRO ANALOGICO 0-150 °C 1/2 NPT", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SWITCHS PRESIÓN DE GAS ALTA Y BAJA HONEYWELL", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "LAMPARA PARA TABLERO SCHNEIDER", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DISCO DESBASTE 7PLG", cantidad: 3, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DISCO DE CORTE 7PLG", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DISCO FLAP 4 1/2PLG", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CAJA PARA PULSADOR NP2B01", cantidad: 6, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SELENOIDE DANFOSS 24VDC- CONEXION 1PLG", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "SELENOIDE STG 220V-CONEXION 1PLG", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "JUEGO DE ACCESORIOS PARA HERMETIZAR TABLERO", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "TERMOMETRO ANALOGICO 0-150 °C", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "EMPAQUE PARA REGISTRO DE MONO CLEAVER BROOKS", cantidad: 6, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "BRIDA CLAMP 2PLG INOX PAR", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CAJA DISPOSITIVO Y CANDADO DE BLOQUEO", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CANDADO BLOQUEO PLASTICO", cantidad: 5, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DISPOSITIVO BLOQUEO GRANDE", cantidad: 5, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "DISPOSITIVO BLOQUEO PEQUEÑO", cantidad: 5, estado: "Nuevo", ubicacion: "Electricista", nivel: "5", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "INTERRUPTOR TERMICO SIEMENS 3X1000A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTOR 3X115 A- 110V", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CONTACTOR LC1G185 AMPERIOS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "RELE TERMICO PARA CONTACTOR 115A", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "LAMPARA LED PARA ILUMINCACIÓN TABLERO", cantidad: 2, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANGUERA NEUMATICA #8 M, ROLLO 100 MTS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "CABLE VULCANIZADO 3X14, DE 50 MTS", cantidad: 1, estado: "Nuevo", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
{ descripcion: "MANIFOLD PARA ELECTROVALVULA SMC", cantidad: 1, estado: "BSU", ubicacion: "Electricista", nivel: "6", fechaIngreso: new Date("2025-06-21"), responsableId: 1 },
  // pega aquí el resto que generes con Excel...
];

async function main() {
  console.log(`Insertando ${items.length} items de inventario...`);

  for (const item of items) {
    try {
      const created = await prisma.inventarioItem.create({ data: item });
      console.log(`✔ Insertado: ${created.id} - ${item.descripcion}`);
    } catch (err) {
      console.error(`✖ Error insertando "${item.descripcion}":`, err.message);
    }
  }

  console.log('Listo.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
